# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-04 09:33
from __future__ import unicode_literals

import simplemde.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jmbo', '0003_auto_20160530_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('modelbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='jmbo.ModelBase')),
                ('question', models.TextField(help_text=b'A question frequently asked by users')),
                ('answer', simplemde.fields.SimpleMDEField(help_text=b'An short but informative answer to the question')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
            },
            bases=('jmbo.modelbase',),
        ),
    ]
