addons:
    postgresql: "9.1"

language: python

python:
  - "2.7"

install:
  - pip install tox
  - pip install -r faq/tests/requirements/19.txt --use-mirrors

before_script:
    - psql -U postgres -c "create database jmbo encoding 'UTF8'"

script: tox
